### ISSUE TITLE
tslint not working and how remove warning on disabled autocompile &

### ISSUE THREAD

**Issue by Master-01** [angelozerr/typescript.java#126]
Hellow!

1) I enabled Preferences -> JavaScript -> TypeScript -> Validation -> Search for 'tslint' from folder (or manualy put path to file tslint.json)
I copy to Project folder file tslint.json 

body tslint.json
{
	"rules": {
        "class-name": true,
        "semicolon": [true, "always"]
       }
}

but TypeScript ignoring line without semicolon like this var a="test"
**How to include a warning that there is no bar in the semicolon?**

2) How to disable a warning on the first line "TypeScript file cannot be compiled on save because tsconfig.json disable it. If this is not intended,  please set "compileOnSave" to "true" of your "tsconfig.json" file." ?
**I specifically do not include the compilation, and do not want to see the warning about it!**

**Comment by angelozerr** [comment]
> but TypeScript ignoring line without semicolon like this var a="test"

Integration of tslint inside typescipt.java is not very good:

 * it works only when you activate TypeScript builder.
 * it works only when you save the editor (as you type validation for tslint doesn't work)
 * it is very slow because each time you save the editor, it executes tslint process: tslint config is loaded, file which is validated is recompiled, etc

To improve the tslint integration (as you type validation, have good performance, etc) we need to wait for https://github.com/Microsoft/TypeScript/pull/10162 https://github.com/Microsoft/TypeScript/issues/6508

And we could even support tslint quick fixes like https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.2.0#quick-fixes

> I specifically do not include the compilation, and do not want to see the warning about it!

You cannot, please create a new issue with that and please share your project which causes your problem.

**Comment by angelozerr** [comment]
@Master-01 tslint integration was improved a lot in 1.2.0:

![](https://github.com/angelozerr/typescript.java/wiki/images/TslintDemo.gif)

See https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.2.0#tslint-integration
