### ISSUE TITLE
TypeScript IDE is great for Phaser Editor!

### ISSUE THREAD

**Issue by boniatillo-com** [angelozerr/typescript.java#127]
Hello Angelo,

This weekend I was playing a bit with typescript ide 1.1.0 and I do not see the moment to include it in the Phaser Editor as the solution for TypeScript and JavaScript programming.
I like the way you are doing the job, everything looks pretty simple to configure at the same time it is configurable and what is more important it works, not only for typescript else for javascript too, with Salsa.

I know it is joung project but probably I will include it as solution for TypeScript programming and as alternative for JavaScript programming.

What is important to me are basic features, like syntax coloring, auto-completions and automatic compilation. Advanced features like refactorings are not so important for me for now.

In relation with JavaScript, the same, what my customers really need is good auto-completion engine and a basic syntax coloring, the rest of the features are not high priority.

Do you think for the release of version 1.2.0 these basic features will get a stable state? If I understand well version 1.2.0 will come with textmate sytanx coloring, but I am worry about the maturity of that project. Is it possible make 1.2.0 to work with the JSDT editor? There is any support for [jsconfig.json](https://code.visualstudio.com/docs/languages/javascript#_javascript-project-jsconfigjson)?

Best regards
Arian

**Comment by angelozerr** [comment]
Hi @boniatillo-com 

> I like the way you are doing the job, everything looks pretty simple to configure at the same time it is configurable and what is more important it works, not only for typescript else for javascript too, with Salsa.

> I know it is joung project but probably I will include it as solution for TypeScript programming and as alternative for JavaScript programming.
ternjs is great but not very active today, that's why I have decided to do the same thing than tern.java with typescript.java with tsserver. Today tsserver is wonderfull but it is not extensible. Once it will be extensible, it will open the door for great features (for angular2, tslint, etc) https://github.com/Microsoft/TypeScript/issues/6508

Thanks! But please note I would like to break the API for typescript client service to use Java8 CompletableFuture. See https://github.com/angelozerr/typescript.java/issues/63 I don't know when I will have time to do this change. I'm very busy with other features.

> like syntax coloring

I think it's stable. By default syntax coloration comes from JSDT, so it should work. , auto-completions and automatic compilation.  You can now use TextMate which improves a lot syntax coloration but it's not by default. See https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.2.0#textmate In other words syntax coloration uses JSDT Java code scanner by defaut and otherwise you can activate TextMate.

> auto-completions

I think it's stable. The completion must be improved for:

 * the second popup (and hover) doesn't render correctly the content. See https://github.com/angelozerr/typescript.java/issues/102
 * async completion (which will be available perhaps for Oxygen)
 
> and automatic compilation. 

If you speak about "compile on save", it should be improved. See https://github.com/angelozerr/typescript.java/issues/109

> Advanced features like refactorings are not so important for me for now.

I have started this feature, but not finish to implement it. See https://github.com/angelozerr/typescript.java/issues/28

> Do you think for the release of version 1.2.0 these basic features will get a stable state? 

syntax coloration is stable (I mean no TextMate), completion is stable, compile is stable, compile on save is not stable. I will try to fix that for 1.2.0 https://github.com/angelozerr/typescript.java/issues/109
 
> If I understand well version 1.2.0 will come with textmate sytanx coloring, but I am worry about the maturity of that project.

Exactly, it's a very young project, but TM4E was accepted by Eclipse.org https://projects.eclipse.org/projects/technology.tm4e I hope I will have more contributions.

> Is it possible make 1.2.0 to work with the JSDT editor?

The textmate features is optionnal. So by default it uses JSDT java scanner.

 Is it possible make 1.2.0 to work with the JSDT editor? There is any support for jsconfig.json?

> There is any support for jsconfig.json?

Like tsconfig.json editor? If it that please create a new issue. But I don't know if I will have time to do that.  For JS I think https://github.com/angelozerr/typescript.java/issues/116 is great feature, but just find time to do that.

**Comment by boniatillo-com** [comment]
Thanks for your comments Angelo. Anyway I will do a release with TS preview, I think many Phaser Editor users will love it.
