### ISSUE TITLE
TypeScript Repository should contains zip

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#152]
I think it should be better than typescript repository contains zip of node_modules because:

 * size of repository will be more small
 * it will avoid some problem if long filename when dev user will get typescript.java from git. @Springrbua I think it's your problem no?

@lorenzodallavecchia what do you think about that?

In other words do like nodejs extension point https://github.com/angelozerr/typescript.java/tree/master/eclipse/embed/ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64

**Comment by Springrbua** [comment]
If thats possible, I guess that would be better.  
Yea I am getting "filename too long", which seems to happen when the directory path gets verry deep and therefore exceeds the 256 character limitation...

**Comment by lorenzodallavecchia** [comment]
I agree: a ZIP is better for sharing on Git.
The only counter-argument is that it must be unzipped on the fly when it is first needed, and that operation may stall the UI.

In an actual RCP application that I work on there are some pretty large shared ZIPs and we resorted to unzipping them at the time of build by using P2 touchpoints.
The only risk of this strategy is having long file paths at the time of installation, but I think it is acceptable because the ZIP _has_ to be expanded at some point.
@Springrbua, out of curiosity, which operation is giving you the "filename to long" error?

So @angelozerr I think the best is to have an expension point that supports both local directory and ZIP, like the nodejs one, leaving the choice to the contributing plugin bundle.
* The default _ts-repository_ bundle that ships with typescript.java would start using a ZIP.
* Other bundles (like the one I am contributing) would keep using a directory and have their own strategy for unzipping (or no strategy at all).

I hope I was clear. Please ask for any doubt.

**Comment by Springrbua** [comment]
@lorenzodallavecchia I got "filename to long", when trying to check out the project.  
I tryed Tortoise GIT as well as Source Tree, both are having this issue.  
I finally managed it using Eclipse EGIT.  
Tortoise GIT still tells me, that I have removed some items from "node_modules/*", because they have to long pathname for Tortoise. So more or less every operation has problems with to long file-/pathname.

**Comment by angelozerr** [comment]
> I hope I was clear. Please ask for any doubt.

Very clear! I agree with you. I will implement that when I will find time.

**Comment by lorenzodallavecchia** [comment]
> I got "filename to long", when trying to check out the project.

Ok, so the problem is with sharing. Putting a ZIP on Git should solve all issues.

**Comment by Springrbua** [comment]
@angelozerr I just wanted to recreate the repository and therefore tryed to delete it on my machine.  
I had the same problem with too long filenames, when trying to delete the project. I needed to rename a lot of folders to contain only a single lettter, so that the filename (including path) became < 256.  
The problem is, that node_module libraries contain other node_module libraries, which contain other node_module libraries etc.  
This creates a verry deep directory-structure, which makes a long pathname.

**Comment by angelozerr** [comment]
@Springrbua just find time to fix this problem, sorry for this disturb -(

**Comment by Springrbua** [comment]
@angelozerr I didn't want to stress you! I just wated to let you know, that the problem is not only with TortoiseGit (and a few other Git-Programs), but with the whole windows-gui too.

**Comment by lorenzodallavecchia** [comment]
While waiting for the fix, if you want to just delete the repository, a possibility is to let npm do the work.
Just move into the _ts.repository_ folder and run `npm uninstall typescript`. Since npm bypasses the Win32 APIs, it should be able to delete long paths.

**Comment by Springrbua** [comment]
@lorenzodallavecchia thanks for this tipp. It would be a lot easier then renaming all the folders do have a shorter path. Thanks!

**Comment by angelozerr** [comment]
@Springrbua I have managed zip of repositories, please tell me if ii resolves your git problem and if it works.

@lorenzodallavecchia please tell me if it works with your custom repository to check I have not broken something. Thanks

**Comment by Springrbua** [comment]
@angelozerr Thats great news, thanks a lot!

**Comment by Springrbua** [comment]
@angelozerr I just tryed to clone my fork of this repository using TortoiseGit and it worked perfectly.  
So this issue can be closed, thanks a lot!

**Comment by angelozerr** [comment]
Very cool news!

**Comment by lorenzodallavecchia** [comment]
> @lorenzodallavecchia please tell me if it works with your custom repository to check I have not broken something

@angelozerr I tried that today and can confirm that my repository extensions still work correctly. Thanks.
