### ISSUE TITLE
Integration with Generic Editor

### ISSUE THREAD

**Issue by boniatillo-com** [angelozerr/typescript.java#168]
It would be great if typescript.java could use GenericEditor instead of JSDT editor, or at least as an alternative.

Actually I think JSDT editor should use the Generic Editor framework, so maybe by using it on typescript.java is a way to show to JSDT devs that it is a viable solution. Then, if JSDT migrates to Generic Editor then typescript can go back to JSDT again.

**Comment by angelozerr** [comment]
typescript.java uses a custom TypeScript editor. It uses some feature of JSDT like JSDT synatx coloration, but since TextMate support exists we could remove this feature.

To be honnest with you, I have no time to remove JSDT dependencies today. I prefer developping new fetaures than remove JSDT dependencies which I think it's an hard task.

**Comment by boniatillo-com** [comment]
Ok then I will close this issue. In any case if I decide to go with it myself then I reopen it.

Thanks.
