### ISSUE TITLE
Navigate to type declaration from reference, not to import 

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#20]

**Comment by angelozerr** [comment]
It's the bahaviour of tsserver. Please suggest your ide to TypeScript.

**Comment by angelozerr** [comment]
@micaelgallego you can try with typescript 2.0.0 (dev), it works:

 * create you a project and do "npm innstall typescript@next"
 * go at Server project preferences and select "${project_loc:node_modules/typescript}" in the installed TypeScript to use typescript 2.0.0

**Comment by micaelgallego** [comment]
Cool!!

Thanks

**Comment by angelozerr** [comment]
This issue is fixed with TypeScript 2.0.3. You can download it or use the embedded ts available in typescript.java 1.1.0:

![](https://github.com/angelozerr/typescript.java/wiki/images/UseTypeScript2AsServer.png)

See https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.1.0#typescript-203 for more information.
